VERBOSE: True

MODEL:
  SESSION: 'Jung'  # Define your current task here

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 2
  NUM_EPOCHS: 20
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 512
  PS_H: 512
  TRAIN_DIR: 'E:/SEM_6/CV/proj/trainonly' # path to training data
  VAL_DIR: 'E:/SEM_6/CV/proj/validonly'    # path to validation data
  SAVE_DIR: 'E:/SEM_6/CV/proj/DocShadow-SD7K/teaser'     # path to save models and images
  ORI: True

TESTING:
  WEIGHT: "E:/SEM_6/CV/proj/DocShadow-SD7K/best_weights/Jung_epoch_15.pth"
  SAVE_IMAGES: True
